
name: test
on: [push, pull_request]
env:
  CI: true
jobs:
  test:
    name: "Test on Node:${{ matrix.node-version }} OS: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10, 12, 14]
        os: [macos-latest, windows-latest, ubuntu-18.04]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Test
        run: |
           git config --global user.email "you@example.com"
           git config --global user.name "Your Name"
           npm test
